# Generated by Django 3.2.7 on 2021-09-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=250)),
                ('price', models.IntegerField(verbose_name=0)),
                ('colour', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('in_stock', models.BooleanField()),
                ('category', models.ManyToManyField(blank=True, related_name='categories', to='gs_server.Category')),
            ],
        ),
    ]
