# Generated by Django 3.2.7 on 2021-09-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs_server', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.IntegerField(),
        ),
    ]
