# Generated by Django 3.2.7 on 2021-09-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gs_server', '0003_alter_shoe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
